###
POST http://192.168.102.171:5000/auth HTTP/1.1
content-type: application/json

{
    "username":"user1",
    "password":"a"
}

###
POST http://192.168.102.171:5000/auth/test HTTP/1.1
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE1NzMxMTc1MDEsIm5iZiI6MTU3MzExNzUwMSwianRpIjoiZWVmNjFlODItYTZiOC00MTZkLTgwZjYtN2Q2MWE2NDhmZDI4IiwiZXhwIjoxNTczMTE4NDAxLCJpZGVudGl0eSI6InVzZXIxIiwiZnJlc2giOmZhbHNlLCJ0eXBlIjoiYWNjZXNzIn0.-JWd9r-kTANPtm5Ru6NMqi9EdM9unrOfFSLLw5g8688
